version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always

  plausible_db:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    image: yandex/clickhouse-server:latest
    volumes:
      - event-data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:latest
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 80:8000 #Remove this line if you plan to use Traefik
    env_file:
      - plausible-conf.env
    labels:
      # Uncomment line below if you plan to use Traefik
      # - "traefik.enable=true"
      # - "traefik.http.routers.plausible.rule=Host(`yourdomain.com`)" # replace this with your own domain
      # - "traefik.http.routers.plausible.entrypoints=websecure"
      # - "traefik.http.services.plausible.loadbalancer.server.port=8000"

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local
